import os
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    POSTGRES_USER: str
    POSTGRES_PASSWORD: str
    POSTGRES_HOST: str
    POSTGRES_DATABASE: str

    PGADMIN_DEFAULT_EMAIL: str
    PGADMIN_DEFAULT_PASSWORD: str

    ZOOKEEPER_CLIENT_PORT: int
    ZOOKEEPER_TICK_TIME: int
    ZOOKEEPER_SYNC_LIMIT: int

    KAFKA_BROKER_ID: int
    KAFKA_ZOOKEEPER_CONNECT: str
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: str
    KAFKA_ADVERTISED_LISTENERS: str
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: int
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: int
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: int
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: int
    KAFKA_JMX_PORT: int

    WAIT_HOSTS: str
    WAIT_HOSTS_TIMEOUT: int
    WAIT_SLEEP_INTERVAL: int
    WAIT_HOST_CONNECT_TIMEOUT: int


settings = Settings(_env_file=os.getenv(".env"))
